# Generated by Django 5.0.6 on 2024-06-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TX', '0002_alter_category_name_alter_category_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorías',
        ),
        migrations.RenameModel(
            old_name='Merchant',
            new_name='Comercios',
        ),
        migrations.RenameModel(
            old_name='Keyword',
            new_name='Keywords',
        ),
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transacciones',
        ),
    ]
