# Generated by Django 5.0.6 on 2024-06-26 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TX', '0005_rename_categorias_category_rename_keywords_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TX.merchant'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TX.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
