# Generated by Django 5.0.6 on 2024-06-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TX', '0007_alter_category_created_at_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorias',
        ),
        migrations.RenameModel(
            old_name='Merchant',
            new_name='Comercios',
        ),
        migrations.RenameModel(
            old_name='Keyword',
            new_name='Keywords',
        ),
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transacciones',
        ),
    ]
