# Generated by Django 5.0.6 on 2024-06-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TX', '0008_rename_category_categorias_rename_merchant_comercios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacciones',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transacciones',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transacciones',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='transacciones',
            name='updated_at',
        ),
    ]
