# Generated by Django 5.0.6 on 2024-06-27 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TX', '0009_remove_transacciones_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TX.categorias'),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TX.comercios'),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
